services:
  web:
    image: portfolio_web:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
     # Persist SQLite database file
      - ./media:/main/media               # Persist media/uploads folder
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
