# Generated by Django 4.1 on 2024-04-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_proefficient_skills_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
