# Generated by Django 4.1 on 2024-04-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=500)),
                ('year', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='work_experience',
            old_name='title',
            new_name='job',
        ),
    ]
