# Generated by Django 4.1 on 2024-04-14 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_certifications_rename_name_projects_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
