# Generated by Django 4.1 on 2024-04-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_certifications_year_alter_education_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='img',
            field=models.ImageField(null=True, upload_to='certs'),
        ),
        migrations.AddField(
            model_name='certifications',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
