# Generated by Django 4.1 on 2024-04-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_certifications_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='img',
            field=models.ImageField(null=True, upload_to='certs'),
        ),
    ]
