# Generated by Django 4.1 on 2024-04-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_certifications_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='description',
        ),
    ]
