# Generated by Django 4.1 on 2024-04-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
