# Generated by Django 4.1 on 2024-04-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_projects_upath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='upath',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
