# Generated by Django 4.1 on 2025-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_projects_upath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='desc',
            field=models.TextField(),
        ),
    ]
