# Generated by Django 4.1 on 2025-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_education_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experience',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='subtitle',
            field=models.TextField(),
        ),
    ]
